// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentions.sql

package db

import (
	"context"
	"time"
)

const createTickerMention = `-- name: CreateTickerMention :one
INSERT INTO ticker_mentions (
  ticker_id,
  user_id,
  comment_id,
  mentioned_at,
  price_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticker_id, user_id, comment_id, price_id, mentioned_at
`

type CreateTickerMentionParams struct {
	TickerID    int64     `json:"ticker_id"`
	UserID      int64     `json:"user_id"`
	CommentID   int64     `json:"comment_id"`
	MentionedAt time.Time `json:"mentioned_at"`
	PriceID     int64     `json:"price_id"`
}

func (q *Queries) CreateTickerMention(ctx context.Context, arg CreateTickerMentionParams) (TickerMention, error) {
	row := q.db.QueryRowContext(ctx, createTickerMention,
		arg.TickerID,
		arg.UserID,
		arg.CommentID,
		arg.MentionedAt,
		arg.PriceID,
	)
	var i TickerMention
	err := row.Scan(
		&i.ID,
		&i.TickerID,
		&i.UserID,
		&i.CommentID,
		&i.PriceID,
		&i.MentionedAt,
	)
	return i, err
}

const getLastTwoMentionsByUsername = `-- name: GetLastTwoMentionsByUsername :many
SELECT
  t.symbol,
  t.id as ticker_id,
  tp.price as mention_price,
  tm.mentioned_at
FROM ticker_mentions tm
JOIN users u ON tm.user_id = u.id
JOIN tickers t ON tm.ticker_id = t.id
JOIN ticker_prices tp ON tm.price_id = tp.id
WHERE u.username = $1
ORDER BY tm.mentioned_at DESC
LIMIT 2
`

type GetLastTwoMentionsByUsernameRow struct {
	Symbol       string    `json:"symbol"`
	TickerID     int64     `json:"ticker_id"`
	MentionPrice string    `json:"mention_price"`
	MentionedAt  time.Time `json:"mentioned_at"`
}

func (q *Queries) GetLastTwoMentionsByUsername(ctx context.Context, username string) ([]GetLastTwoMentionsByUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, getLastTwoMentionsByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLastTwoMentionsByUsernameRow
	for rows.Next() {
		var i GetLastTwoMentionsByUsernameRow
		if err := rows.Scan(
			&i.Symbol,
			&i.TickerID,
			&i.MentionPrice,
			&i.MentionedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
