// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicker(ctx context.Context, arg CreateTickerParams) (Ticker, error)
	CreateTickerMention(ctx context.Context, arg CreateTickerMentionParams) (TickerMention, error)
	CreateUser(ctx context.Context, username string) (User, error)
	GetCommentByUserAndExternalID(ctx context.Context, arg GetCommentByUserAndExternalIDParams) (Comment, error)
	GetFirstMentionPerTickerByUsername(ctx context.Context, username string) ([]GetFirstMentionPerTickerByUsernameRow, error)
	GetLatestTickerPrice(ctx context.Context, tickerID int64) (GetLatestTickerPriceRow, error)
	GetTickerBySymbol(ctx context.Context, symbol string) (Ticker, error)
	GetTickerPriceByDate(ctx context.Context, arg GetTickerPriceByDateParams) (GetTickerPriceByDateRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertTickerPrice(ctx context.Context, arg InsertTickerPriceParams) (TickerPrice, error)
	ListAllTickers(ctx context.Context) ([]Ticker, error)
	TickerPriceExistsForDate(ctx context.Context, arg TickerPriceExistsForDateParams) (bool, error)
	UpsertTicker(ctx context.Context, arg UpsertTickerParams) error
}

var _ Querier = (*Queries)(nil)
