// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickers.sql

package db

import (
	"context"
)

const createTicker = `-- name: CreateTicker :one
INSERT INTO tickers (symbol, company_name, exchange)
VALUES ($1, $2, $3)
RETURNING id, symbol, company_name, exchange, currency, created_at
`

type CreateTickerParams struct {
	Symbol      string `json:"symbol"`
	CompanyName string `json:"company_name"`
	Exchange    string `json:"exchange"`
}

func (q *Queries) CreateTicker(ctx context.Context, arg CreateTickerParams) (Ticker, error) {
	row := q.db.QueryRowContext(ctx, createTicker, arg.Symbol, arg.CompanyName, arg.Exchange)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.CompanyName,
		&i.Exchange,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getTickerBySymbol = `-- name: GetTickerBySymbol :one
SELECT id, symbol, company_name, exchange, currency, created_at
FROM tickers
WHERE symbol = $1
`

func (q *Queries) GetTickerBySymbol(ctx context.Context, symbol string) (Ticker, error) {
	row := q.db.QueryRowContext(ctx, getTickerBySymbol, symbol)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.CompanyName,
		&i.Exchange,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listAllTickers = `-- name: ListAllTickers :many
SELECT id, symbol, company_name, exchange, currency, created_at FROM tickers ORDER BY symbol
`

func (q *Queries) ListAllTickers(ctx context.Context) ([]Ticker, error) {
	rows, err := q.db.QueryContext(ctx, listAllTickers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticker
	for rows.Next() {
		var i Ticker
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.CompanyName,
			&i.Exchange,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTicker = `-- name: UpsertTicker :exec
INSERT INTO tickers (symbol, company_name, exchange)
VALUES ($1, $2, $3)
ON CONFLICT (symbol) DO NOTHING
`

type UpsertTickerParams struct {
	Symbol      string `json:"symbol"`
	CompanyName string `json:"company_name"`
	Exchange    string `json:"exchange"`
}

func (q *Queries) UpsertTicker(ctx context.Context, arg UpsertTickerParams) error {
	_, err := q.db.ExecContext(ctx, upsertTicker, arg.Symbol, arg.CompanyName, arg.Exchange)
	return err
}
